config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  broadcasts_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title 
    has_rich_text :content
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post 

    def create 
        @post.comments.create! params.required(:comment).permit(:content)
        redirect_to @post
    end

    private 
    def set_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.image? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>
  <% if blob.video? %>
    <%= video_tag url_for(blob.attachable),
    preload: 'auto',
    controls: 'controls',
    padding: '0px',
    margin: '0px',
    height: '100%',
    width: '100%' %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div style="border-radius: 15px; border-bottom:1px solid black;">
<div id="<%= dom_id(comment) %>", >
<%= comment.content %>
- <%= time_tag comment.created_at, "data-local": "time-ago" %>
</div></div>

app/views/comments/_new.html.erb
<%= form_with model: [ post, Comment.new ] do |form| %>
<br>
<%= form.text_area :content, size: "20x5", placeholder:"COMMENT HERE",style:"text-align:center;" %>
<%= form.submit %>
<% end %>

app/views/home/index.html.erb
<h1>RAILS 7</h1>
<p>THIS IS MY RAILS 7 BLOG</p>


<div class="container">
<div class="card" style='border-radius:15px; border: 2px solid black; background-color:white; color:blue; height:fit-content; width:300px''>
  <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages4.alphacoders.com%2F922%2Fthumb-1920-922300.jpg&f=1&nofb=1" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="padding:1px">View Blogs</h5>
    <p class="card-text"> Join A Discussion</p>
    <a href="/posts" class="btn btn-primary">View Blogs</a>
  </div>
</div>


<div class="card" style='border-radius:15px; border: 2px solid black; background-color:white; color:blue; height:fit-content; width:300px''>
  <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fassets.change.org%2Fphotos%2F9%2Flz%2Fzq%2FSjLzzqoSIOdDwqH-1600x900-noPad.jpg%3F1515333742&f=1&nofb=1" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Start a New Blog</h5>
    <p class="card-text">Start A Conversation </p></p>

    <a href="/posts/new" class="btn btn-primary">New Post</a>
  </div>
</div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kingthor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<h3>comments</h3>

<div id="comments">
 <p>
<%= pluralize post.comments.count, "comment" %>
</p>
<%= render post.comments %>

</div>
<%= render "comments/new", post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card" style="width: 75%; border:1px solid black; border-radius:15px;">
<div class="card-body">
  <div class="card-title">
    
    <%= form.text_field :title, placeholder:"TITLE" %>
  </div>

  <div class="card-subtitle">
   <br>
    <%= form.rich_text_area :content , placeholder:"CONTENT", style:"text-align:center"%>
  </div>

  <div class="card-subtitle">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong><%= post.title %></strong>
    
  </p>

  <h3>
    
    <%= post.content %>
  </h3>
 <p>
  Posted <%= time_tag post.created_at, "data-local": "time-ago" %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to  "home", home_index_path %>  <%= link_to "New post", new_post_path %>
<h1>Posts</h1>

  <% @posts.each do |post| %>
  <div class="card" style="border:1px solid black; border-radius:15px; color:black; width:600px">
  <div id="posts" class="card-body" style="text-align:center">
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
    </div>
    </div>
  <% end %>

app/views/posts/new.html.erb
<div>
  <%= link_to "Back to posts", posts_path %> |
  <%= link_to 'Home', home_index_path %>
</div>
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>
<%= link_to  "home", home_index_path %>
<p style="color: green"><%= notice %></p>
<div class="card" style="width: 75%; border:1px solid black; border-radius:15px; color:black">
<div class="cardbody" style="text-align:center;">
<%= render @post %>
<%= render "posts/comments", post: @post%>
</div>
<div class="card-subtitle">
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
</div>